# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='notes',
            field=models.TextField(default='no notes'),
        ),
    ]
