# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 20:12
from __future__ import unicode_literals

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180409_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='none', max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='none', max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='none', max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=255, validators=[apps.users.models.password_validation]),
            preserve_default=False,
        ),
    ]
