# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 15:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180318_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
