# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 10:05
from __future__ import unicode_literals

import apps.user_settings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=False)),
                ('txt', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=12, validators=[apps.user_settings.models.phone_validation])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.User')),
            ],
        ),
    ]
